version: "3.3"

networks:
  llauai:

services:

  # nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www/project
      - ./logs:/var/log/nginx
      - ./config/ssls:/etc/nginx/ssls
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-service
    networks:
      - llauai

  # php
  php-service:
    build: 
      context: .
      dockerfile: ./config/php/Dockerfile
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    container_name: php-container
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/project
      - ./config/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - llauai

  # postgres
  db:
    image: postgres:16.3-alpine
    container_name: postgres-container
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER_NAME}
      - POSTGRES_PASSWORD=${DB_USER_PSWD}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - llauai

  # adminer
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - llauai